version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    container_name: department
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=19A12iou#
      - POSTGRES_USER=root
      - POSTGRES_DB=employee